### ISSUE TITLE
Re-code site

### ISSUE THREAD

**Issue by jackmawer** [jackmawer/Teenage-Programmers-Website#6]
I'd like to recode and prettify the site at some point.

**Comment by gtomitsuka** [comment]
Well, @DebonairStudios prettified the site not long ago.

**Comment by jackmawer** [comment]
I'm unhappy with it still.

**Comment by Jacob-Gray** [comment]
@jackmawer so am I, i am working on another version :santa:

**Comment by jackmawer** [comment]
Don't have time for this right now, and it actually looks fine rn.
